config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  ########### CANDIDATES AREA ###########
  devise_for :candidates, controllers: {
    sessions: 'candidates/sessions',
    registrations: 'candidates/registrations',
    passwords: 'candidates/passwords'
  }

  namespace :candidate, path: "candidato" do
    get   '/user-login'                 , to: 'steps#login_or_register' , as: :login_or_register
    get   '/pre-register'               , to: 'steps#pre_register'      , as: :pre_register
    get   '/termos'                     , to: 'steps#terms'             , as: :terms
    match '/detalhes-rapidos'           , to: 'steps#quick_details'     , as: :quick_details , via: [:get, :post]
    get   '/completar-registro'         , to: 'steps#complete_register' , as: :complete_register
    post  '/completar-registro'         , to: 'steps#create_candidate'  , as: :create_candidate
    get   '/boas-vindas'                , to: 'steps#welcome_message'   , as: :welcome_message
    get   '/dashboard'                  , to: 'dashboard#index'         , as: :dashboard

    ##### INTEREST SECTOR #####
    get   'interesse/primeira-etapa'    , to: 'interest#transition'   , as: :first_transition
    get   'interesse/passo-1'           , to: 'interest#first'        , as: :interest_step_1
    match 'interesse/passo-2'           , to: 'interest#second'       , as: :interest_step_2         , via: [:get, :post]
    match 'interesse/passo-3'           , to: 'interest#third'        , as: :interest_step_3         , via: [:get, :post]
    match 'interesse/passo-4'           , to: 'interest#fourth'       , as: :interest_step_4         , via: [:get, :post]
    match 'interesse/passo-5'           , to: 'interest#fifth'        , as: :interest_step_5         , via: [:get, :post]
    post  'interesse/passo-completo'    , to: 'interest#complete'     , as: :interest_step_complete

    ##### MAIN CANDIDATE AREA #####
    get  '/home'                        , to: 'main#home'             , as: :home
    get  '/perfil'                      , to: 'main#profile'          , as: :profile
    post '/atualizar-perfil'            , to: 'main#update_profile'   , as: :update_profile

    ##### EXPERIENCE SECTOR #####
    get   'experiencia/segunda-etapa'   , to: 'experience#transition' , as: :second_transition
    get   'experiencia/passo-1'         , to: 'experience#first'      , as: :experience_step_1
    match 'experiencia/passo-2'         , to: 'experience#second'     , as: :experience_step_2        , via: [:get, :post]
    match 'experiencia/passo-3'         , to: 'experience#third'      , as: :experience_step_3        , via: [:get, :post]
    match 'experiencia/passo-4'         , to: 'experience#fourth'     , as: :experience_step_4        , via: [:get, :post]
    match 'experiencia/passo-5'         , to: 'experience#fifth'      , as: :experience_step_5        , via: [:get, :post]
    match 'experiencia/passo-6'         , to: 'experience#sixth'      , as: :experience_step_6        , via: [:get, :post]
    match 'experiencia/passo-7'         , to: 'experience#seventh'    , as: :experience_step_7        , via: [:get, :post]
    post  'experiencia/passo-completo'  , to: 'experience#complete'   , as: :experience_step_complete

    #### COMPANY SECTOR #####
    get   'empresa/terceira-etapa'      , to: 'company#transition'    , as: :third_transition
    get   'empresa/passo-1'             , to: 'company#first'         , as: :company_step_1
    match 'empresa/passo-2'             , to: 'company#second'        , as: :company_step_2           , via: [:get, :post]
    match 'empresa/passo-3'             , to: 'company#third'         , as: :company_step_3           , via: [:get, :post]
    post  'empresa/passo-completo'      , to: 'company#complete'      , as: :company_step_complete

    get   'empresa/bairros'             , to: 'company#neighborhoods' , as: :neighborhoods
    get   'empresa/subsetores'          , to: 'company#subsectors'    , as: :subsectors

    #### HABILITY SECTOR #####
    get  'habilidade/passo-1'           , to: 'hability#first'        , as: :hability_step_1
    post 'habilidade/passo-completo'    , to: 'hability#complete'     , as: :hability_step_complete

    #### EDUCATION SECTOR #####
    get   'educacao/passo-1'            , to: 'education#first'       , as: :education_step_1
    match 'educacao/passo-2'            , to: 'education#second'      , as: :education_step_2          , via: [:get, :post]
    post  'educacao/passo-completo'     , to: 'education#complete'    , as: :education_step_complete

    #### PRETENSION SECTOR #####
    get   'pretensao/passo-1'           , to: 'pretension#first'      , as: :pretension_step_1
    match 'pretensao/passo-2'           , to: 'pretension#second'     , as: :pretension_step_2         , via: [:get, :post]
    post  'pretensao/complete'          , to: 'pretension#complete'   , as: :pretension_step_complete
  end


  ########### COMPANIES AREA ###########
  devise_for :companies, controllers: {
    sessions: 'companies/sessions',
    registrations: 'companies/registrations',
    passwords: 'companies/passwords'
  }

  namespace :company, path: "empresa" do
    get   '/company-login'              , to: 'steps#login_or_register', as: :login_or_register
    get   '/termos'                     , to: 'steps#terms'            , as: :terms
    post  '/termos'                     , to: 'steps#create_company'   , as: :create_company

    ##### MAIN COMPANY AREA #####
    get  '/home'                        , to: 'main#home'             , as: :home
    get  '/perfil'                      , to: 'main#profile'          , as: :profile
    post '/atualizar-perfil'            , to: 'main#update_profile'   , as: :update_profile

    ##### MAIN USER COMPANY AREA #####
    get  '/usuario/perfil'              , to: 'user#profile'          , as: :company_user_profile


    #### ABOUT SECTOR #####
    get   'sobre/passo-1'               , to: 'about#first'             , as: :about_step_1
    match 'sobre/passo-2'               , to: 'about#second'            , as: :about_step_2         , via: [:get, :post]
    match 'sobre/passo-3'               , to: 'about#third'             , as: :about_step_3         , via: [:get, :post]
    match 'sobre/passo-4'               , to: 'about#fourth'            , as: :about_step_4         , via: [:get, :post]
    match 'sobre/passo-5'               , to: 'about#fifth'             , as: :about_step_5         , via: [:get, :post]
    post  'sobre/passo-completo'        , to: 'about#complete'          , as: :about_step_complete

    #### FILTER CANDIDATE AREA #####
    get   'buscar-candidato/passo-1'    , to: 'filter_candidate#first'  , as: :filter_step_1
    match 'buscar-candidato/passo-2'    , to: 'filter_candidate#second' , as: :filter_step_2, via: [:get, :post]
    match 'buscar-candidato/passo-3'    , to: 'filter_candidate#third'  , as: :filter_step_3, via: [:get, :post]
    match 'buscar-candidato/passo-4'    , to: 'filter_candidate#fourth' , as: :filter_step_4, via: [:get, :post]
    match 'buscar-candidato/passo-5'    , to: 'filter_candidate#fith'   , as: :filter_step_5, via: [:get, :post]

    #### CANDIDATE PROFILE AREA #####
    get   'candidato/perfil'                           , to: 'candidate#profile'        , as: :candidate_profile
    get   'candidato/perfil-confidencial'              , to: 'candidate#blind_profile'  , as: :candidate_profile_blind
    put   'candidato/perfil/:candidate_id/update-state', to: 'candidate#update_state'
    get   'candidato/perfil/:id'                       , to: 'candidate#profile'        , as: :candidate_profile_view

    #### SELECTIVE PROCESS AREA #####
    get   '/processo-seletivo/info'     , to: 'selective_process#info'
    get   '/processo-seletivo/:state'   , to: 'selective_process#index' , as: :selective_process

    #### COMPANY NOTICES AREA #####
    get   '/avisos-conta'               , to: 'notices#index'           , as: :notices
  end


  ########### ADMINS AREA ###########
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords'
  }

  mount LoldesignPublisher::Rails::Engine => '/'

  get '/admin', to: 'admin/areas#index'

  namespace :admin do
    resources :admins,                  path: :administradores
    resources :positions,               path: :cargos
    resources :specialties,             path: :especialidades
    resources :translations,            path: :translations
    resources :terms,                   path: :termos
    resources :package_services,        path: :'pacotes-de-servico'
    resources :locales,                 path: :localidades
    resources :sectors,                 path: :setores
    resources :company_sizes,           path: :portes
    resources :modes,                   path: :modes
    resources :relevances,              path: :relevancias
    resources :title_lists,             path: :'lista-de-titulos'
    resources :range_lists,             path: :'lista-de-alcances'
    resources :education_lists,         path: :'lista-de-escolaridades'
    resources :language_lists,          path: :'lista-de-linguas'
    resources :language_level_lists,    path: :'lista-de-niveis_linguas'
    resources :nofsalaries_lists,       path: :'lista-de-nofsalaries'
    resources :benefits_lists,          path: :'lista-de-beneficios'
    resources :annual_claim_rate_lists, path: :'lista-de-reivindicacoes'
    resources :status_lists,            path: :'lista-de-status'
    resources :step_lists,              path: :'lista-de-etapas'
    resources :sort_lists,              path: :'lista-de-odernações'
    resources :areas,                   path: :areas  do
      resources :functions, path: :funcoes do
        resources :habilities, path: :habilidades
      end
    end
    resources :states,                  path: :estados do
      resources :cities, path: :cidades do

app/controllers/candidate/company_controller.rb
class Candidate::CompanyController < ApplicationController 
  before_action :authenticate_candidate!
  before_action :set_candidate, only: [:first, :second, :third, :complete]

  def first
    @current_company = @candidate_current_company
    @manager         =  CandidateInfoManager.new(candidate: @candidate)

    @months = arrayForSelect(1, 12)
    @years  = arrayForSelect(1990, Date.today.year)

    # if params[:candidate_current_company].present?
    #   manager = CandidateManager.new(candidate_current_company: @current_company, candidate_current_company_params: candidate_current_company_params)
    #   saved = manager.update_candidate_current_companies
    #   if !saved
    #     @start_date_error_present = @current_company.errors.present? && (@current_company.errors[:start_date_month].present? || @current_company.errors[:start_date_year].present? || @current_company.errors[:start_date].present?)
    #     @end_date_error_present   = @current_company.errors.present? && (@current_company.errors[:end_date_month].present? || @current_company.errors[:end_date_year].present?)
    #     load_size_sector_and_profile
    #     @city = City.all
    #     @city_locale = CityLocale.all
    #     @neighborhood = Neighborhood.all
    #     render action: :first
    #   end
    # end

    @companies = @candidate_companies.empty? ? [CandidateCompany.new] : @candidate_companies
  end

  def second
    manager = CandidateManager.new(candidate: @candidate, candidate_company_params: candidate_company_params)
    manager.create_or_update_candidate_companies

    @companies = @candidate_companies.empty? ? [CandidateCompany.new] : @candidate_companies

    load_size_sector_and_profile
    @city = City.all
    @city_locale = CityLocale.all
    @neighborhood_group = NeighborhoodGroup.all
    @neighborhoods = Neighborhood.all

    if !@candidate.valid? || @candidate.candidate_companies.empty?
      redirect_to action: :first
    else
      @companies = @candidate.candidate_companies
      load_size_sector_and_profile
      @subsectors = Subsector.all
    end
  end

  def third
    manager = CandidateManager.new(candidate: @candidate, candidate_company_params: candidate_company_params)
    manager.create_or_update_candidate_companies
  end

  def complete
    manager = CandidateManager.new(candidate_company_params: candidate_company_params)
    saved   = manager.update_all_candidate_companies
    if !saved
      redirect_to action: :second
    else
      @candidate.completed_companies! if @candidate.reload.companies?

      redirect_to candidate_hability_step_1_path
    end
  end

  def neighborhoods
    neighborhood_group = NeighborhoodGroup.find(params[:neighborhood_group_id])

    if neighborhood_group.present?
      @neighborhoods = neighborhood_group.neighborhoods

      render json: @neighborhoods
    else
      render json: {status: 422}
    end
  end

  def subsectors
    sector = Sector.find(params[:sector_id])

    if sector.present?
      @subsectors = sector.subsectors

      render json: @subsectors
    else
      render json: {status: 422}
    end
  end

  private
    def set_candidate
      @candidate = current_candidate
      @candidate_companies = @candidate.candidate_companies
      @candidate_current_company = @candidate.candidate_current_company
    end

    def candidate_company_params
      if params[:candidate_companies].present?
        params.fetch(:candidate_companies, {}).map do |p|
          p.permit(:id, :name, :months, :nationality, :size, :sector, :subsector, :title,
            :start_date_month, :start_date_year, :end_date_month, :end_date_year
          )
        end
      end
    end

    def candidate_current_company_params
      params.fetch(:candidate_current_company, {}).permit(:id, :name, :start_date, :end_date, :start_date_month, :start_date_year, :end_date_month, :end_date_year, :currently_work_here, :nationality, :company_size, :sector, :subsector, :mode, :city, :city_locale, :neighborhood_group, :neighborhood, :corporate_email)
    end

    def arrayForSelect(min, max)
      array = []
      for i in min..max
        if i < 10
          array << ["0#{i}", "#{i}"]
        else
          array << ["#{i}", "#{i}"]
        end
      end
      array
    end

    def load_size_sector_and_profile
      @size       = CompanySize.all
      @sector     = Sector.all
      @subsectors = []
      @profile    = Mode.all
    end
end

app/controllers/candidate/main_controller.rb
class Candidate::MainController < ApplicationController
  before_action :authenticate_candidate!
  before_action :set_candidate
  before_action :validate_params, only: :update_profile

  def home
    @header_options = {style: :dashboard_header}
    @tab_bar        = {style: :with_tab_bar}

    @sectors       = Sector.where("id IN (?)", @candidate.candidate_interest.sectors)
    @company_sizes = CompanySize.where("id IN (?)", @candidate.candidate_interest.company_sizes)
    @modes         = Mode.where("id IN (?)", @candidate.candidate_interest.modes)
    @city_locales  = CityLocale.joins(:neighborhoods).where('neighborhoods.id IN (?)', @candidate.candidate_interest.neighborhoods).distinct
  end

  def profile
    @current_company = @candidate.candidate_current_company
    @header_options  = {style: :dashboard_header}
    @tab_bar         = {style: :with_tab_bar}
  end

  def update_profile
    @current_company = @candidate.candidate_current_company.present? ? @candidate.candidate_current_company : @candidate.build_candidate_current_company

    if current_candidate.update_attributes(candidate_params) && (params[:candidate_current_company].present? && @current_company.update_attributes(candidate_current_company_params))
      redirect_to candidate_profile_path
    else
      @header_options = {style: :dashboard_header}
      @tab_bar        = {style: :with_tab_bar}
      
      render :profile
    end
  end

  private
  def validate_params
    redirect_to candidate_profile_path(current_candidate) unless params[:candidate].present?
  end

  def set_candidate
    @candidate = current_candidate
  end
  
  def candidate_params 
    params.require(:candidate).permit(:candidate_avatar, :candidate_curriculum, :new_challenges, :employed)
  end

  def candidate_current_company_params
    params.require(:candidate_current_company).permit(:corporate_email)
  end
end

app/controllers/companies/confirmations_controller.rb
# frozen_string_literal: true

class Companies::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/companies/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Companies::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/company/notices_controller.rb
class Company::NoticesController < ApplicationController 
  
end 

app/views/company/main/_company_infos.html.erb
<section class="company-infos-container">
  <header>
    <h3 class="bold">Nestlé</h3>
    <i class="material-icons">edit</i>
  </header>

  <div class="company-infos-box">
    <div class="company-infos">
      <p class="bold">
        Vila Olimpia
      </p>

      <p class="bold">
        Grande
      </p>

      <p class="bold">
        Bens de Consumo
      </p>

      <p class="bold">
        Conservador
      </p>

      <p class="bold">
        Candidatos do setor
      </p>
    </div>

    <div class="company-account-status">
      <p class="bold">Conta Ativa</p>

      <div class="button-box">
        <button>Plano</button>
      </div>
    </div>
  </div>
</section>

app/views/company/main/home.html.erb
<section id="complete_company_register" class="question-container content">
  <section class="title">
    <h4 class="light-green-text bold main-title">
      Encontre novos candidatos para sua empresa!
    </h4>
  </section>

  <section class="action-buttons-single">
    <%= link_to "CONTINUAR", @process_selection.setting? ? company_filter_step_1_path : company_candidate_profile_path, class: "waves-effect waves-light btn-large" %>
  </section>
</section>

app/views/company/main/profile.html.erb
<section id="company_profile">
  <section class="left-box">
    <%= render :partial => "company_infos" %>

    <section class="add-user-container shadow-box">
      <p>Adicionar Usuário</p>

      <div class="add-user-field">
        <div class="default-bg">
          <i class="material-icons">person_add</i>
        </div>

        <%= text_field_tag 'add_company_user', "", class: 'form-control', placeholder: 'email empresa' %>

        <%= submit_tag "Autorizar", class: "submit-action", data: { disable_with: "..." } %>
      </div>
    </section>
  </section>
  
  <section class="right-box">
    <section class="company-active-users-container shadow-box">
      <p>Usuários Ativos</p>
      <ul>
        <li class="active-user-item">
          <div class="default-bg">
            <i class="material-icons">person</i>
          </div>

          <div class="active-user-info">
            <p class="bold">Rebecca Silva</p>
            <p class="bold">Diretor - RH</p>
          </div>

          <%= submit_tag "Desativar", class: "submit-action", data: { disable_with: "..." } %>
        </li>

        <li class="active-user-item">
          <div class="default-bg">
            <i class="material-icons">person</i>
          </div>

          <div class="active-user-info">
            <p class="bold">Martins dos Santos</p>
            <p class="bold">Coordenador - RH</p>
          </div>

          <%= submit_tag "Desativar", class: "submit-action", data: { disable_with: "..." } %>
        </li>

        <li class="active-user-item">
          <div class="default-bg">
            <i class="material-icons">person</i>
          </div>

          <div class="active-user-info">
            <p class="bold">Silvana Fisher (Admin)</p>
            <p class="bold">Gerente - Marketing</p>
          </div>

          <%= submit_tag "Desativar", class: "submit-action", data: { disable_with: "..." } %>
        </li>

        <li class="active-user-item">
          <div class="default-bg">
            <i class="material-icons">person</i>
          </div>

          <div class="active-user-info">
            <p class="bold">Laura Gouveia</p>
            <p class="bold">Gerente - Finanças</p>
          </div>

          <%= submit_tag "Desativar", class: "submit-action", data: { disable_with: "..." } %>
        </li>
      </ul>
    </section>

    <section class="company-user-solicitations-container shadow-box">
      <p>Solicitações</p>
      <ul>
        <li class="active-user-item">
          <div class="default-bg">
            <i class="material-icons">person</i>
          </div>

          <div class="active-user-info">
            <p class="bold">Paulo Augusto</p>
            <p class="bold">Analista - Controladoria</p>
          </div>

          <%= submit_tag "Autorizar", class: "submit-action", data: { disable_with: "..." } %>
        </li>

        <li class="active-user-item">
          <div class="default-bg">
            <i class="material-icons">person</i>
          </div>

          <div class="active-user-info">
            <p class="bold">Ubirajá Santos</p>
            <p class="bold">Analista - Contábil</p>
          </div>

          <%= submit_tag "Autorizar", class: "submit-action", data: { disable_with: "..." } %>
        </li>
      </ul>
    </section>
  </section>
</section>